runtime: nodejs20
instance_class: F1

handlers:
# This one handler sends ALL traffic to your Node.js server
- url: /.*
  script: auto

# Make sure your environment variables are set
env_variables:
  NODE_ENV: production
  PORT: 8080
  TM_API_KEY: Pw0ENtXN5YXCOjYdlkCGAD0TsSV4mcXC
  GOOGLE_API_KEY: AIzaSyBlbMWz8nLKESmKj4C5mZXHdPCnLJlDf3o
  IPINFO_TOKEN: 3ef8c463a0953f